# WriteOutput.R
# This script writes the output from Run.R into various formats to allow further calculations
# Main outputs:
# 1. VISION files to allow calculation of MS and OS loads in VISION
# 2. Excel files for high level analysis of key scenarios
# 3. Excel files for Financial model to determine required investments
# 4. RData structure for visualisation of output in Tableau 
#
# By Joris van der Els
# Based on code generated by Werner van Westering
# Start 21-12-2014
#
##Initialize ----------------------------------------------------------------------
# Remove all data and set working directory
rm(list=ls(all=TRUE))
gc(verbose=FALSE)
path = "C:/1. Programmeerwerk/Bottum Up Analyse/2. Data"
setwd(paste0(path,"/7. Output"))

print("--Loading packages--")
# Load packages
library(reshape2)
library(plyr)
library(data.table)
library(slam)       #Used for sparse matrices
library(tictoc)     #Because I am a Matlab person
library(xlsx)
library(ggplot2)
library(gmodels)

#Load data (To generate this data: run Run.R)
print("--Loading data--")
load("CalculationOutput_NH_v2.RData")

# Export to VISION ----------------------------------------------------------------------------------------------
# Vision requires a very specific output format. The script is quick & dirty. At least some of it is commented!
indexlist      = match(MSRlist,Vnames$NR_Behuizing_NRG)        # Cannot match 362 stations
Visionlist     = Vnames$ID_Vision[indexlist]                   # Sort the list of MSR's in the Vision order
NAlist         = is.na(Visionlist)==FALSE                      # Create a list of MSR that have not been found
exportnamelist = Visionlist[NAlist]                            # Only use the found MSR for the export
# NAlist       = c(NAlist,NAlist*2,NAlist*3,NAlist*4)            
MSRexport      = MSRload[NAlist,]
MSRexportmin   = MSRloadmin[NAlist,]
MSRmaxexport   = MSRmax[NAlist]
nMSR           = length(exportnamelist)
indexlist      = c(seq(1,nMSR*4*nscenarios,by=4),seq(2,nMSR*4*nscenarios,by=4),seq(3,nMSR*4*nscenarios,by=4),seq(4,nMSR*4*nscenarios,by=4))
startyear      = 2014 #Sloppy! Needed to be declared here for output but should be moved to DataPreparation.R!!
endyear        = 2030 #Sloppy! Needed to be declared here for output but should be moved to DataPreparation.R!!
years          = seq(startyear,endyear)
nyears         = length(years)
datelist       = c(paste(rep_len(paste(years-2000,rep_len("-",nyears),rep.int(1,nyears),rep_len("-",nyears)),nscenarios),floor(seq.int(2001,2001+nscenarios/nyears,1/nyears))[1:nscenarios]))
timelist       = rep.int(9,nscenarios)
exportbaseload = matrix(t(MSRexport)[indexlist],nscenarios,(nMSR*4))     # Reshape results for saving in Vision format
#exportbaseloadmin = matrix(t(MSRexportmin)[indexlist],nscenarios,(nMSR*4))     # Reshape results for saving in Vision format

#Set VISION output files and column names
exportname = c('Datum','Tijd',paste(exportnamelist,'.Bel1',sep=''),paste(exportnamelist,'.PV',sep=''),paste(exportnamelist,'.EV',sep=''),paste(exportnamelist,'.WP',sep='')) #Setup the specific Vision names
dt = data.table(datelist,timelist,exportbaseload)  #Convert exportmatrix to datatable because R is not capable enough to save matrices
setnames(dt,exportname)             #Set the column names
dt2 = data.table(scenarionumber)
setnames(dt2,c('Year','PV scenario', 'EV scenario', 'WP scenario', 'peak time index', 'minimum time index'))

setwd(paste0(path,"/7. Output/1. VISION"))
#write CSVs for VISION
#for (ii in 0:(nscenarios/(4*nyears))-1) {
#  dtprint = dt[(1+ii*(4*nyears)):((ii+1)*(4*nyears)),]
#  name = paste0("MSRloadvision_",(1+ii*(4*nyears)),"-",((ii+1)*(4*nyears)),".csv")
#  write.csv2(dtprint,name,row.names=FALSE)
#}

write.csv2(dt[1:68,],"MSRloadvision_1.csv",row.names=FALSE)
write.csv2(dt[69:136,],"MSRloadvision_2.csv",row.names=FALSE)
write.csv2(dt[137:204,],"MSRloadvision_3.csv",row.names=FALSE)
write.csv2(dt[205:272,],"MSRloadvision_4.csv",row.names=FALSE)
write.csv2(dt[273:340,],"MSRloadvision_5.csv",row.names=FALSE)
write.csv2(dt[341:408,],"MSRloadvision_6.csv",row.names=FALSE)
write.csv2(dt[409:476,],"MSRloadvision_7.csv",row.names=FALSE)
write.csv2(dt[477:544,],"MSRloadvision_8.csv",row.names=FALSE)
write.csv2(dt[545:612,],"MSRloadvision_9.csv",row.names=FALSE)
write.csv2(dt[613:680,],"MSRloadvision_10.csv",row.names=FALSE)
write.csv2(dt[681:748,],"MSRloadvision_11.csv",row.names=FALSE)
write.csv2(dt[749:816,],"MSRloadvision_12.csv",row.names=FALSE)

write.csv2(dt2, "Scenarioindex.csv",)

# Export to Excel for analysis ----------------------------------------------------------------------------------
#Presentation_maxfeedin = [high PV, Low EV, low WP] = [3,1,1]
#Presentation_average = [medium PV, medium EV, medium WP] = [1,3,4]
#Presentation_maxload = [low PV, High EV, High WP] = [2,2,2]
#select correct rows from output. 
setwd(path)
Presentation_maxload =  c(1,3,4) #[medium PV, medium EV, medium WP]
Presentation_average = c(2,2,2) #[low PV, High EV, High WP]
Presentation_maxfeedin = c(3,1,1) #[high PV, Low EV, low WP]
index_maxload = seq(1 + ((Presentation_maxload[1]-1)* (nscenarios/3)) + ((Presentation_maxload[2]-1)* (nscenarios/12)) + ((Presentation_maxload[3]-1)* (nscenarios/48)),length.out=17)
index_average = seq(1 + ((Presentation_average[1]-1)* (nscenarios/3)) + ((Presentation_average[2]-1)* (nscenarios/12)) + ((Presentation_average[3]-1)* (nscenarios/48)),length.out=17)
index_maxfeedin = seq(1 + ((Presentation_maxfeedin[1]-1)* (nscenarios/3)) + ((Presentation_maxfeedin[2]-1)* (nscenarios/12)) + ((Presentation_maxfeedin[3]-1)* (nscenarios/48)),length.out=17)
index_scenarios = c(index_maxload,index_average,index_maxfeedin)

MSRmaxexportaangevuld = c(MSRmaxexport,rep(0,3*nMSR))

dt = data.table(scenarionumber[index_scenarios,1:4],exportbaseload[index_scenarios,])
exportname = c('Jaar','PV scenario','EV scenario','WP scenario',paste(exportnamelist,'.Bel1',sep=''),paste(exportnamelist,'.PV',sep=''),paste(exportnamelist,'.EV',sep=''),paste(exportnamelist,'.WP',sep=''))
dt = data.table(exportname,c(0,0,0,0,MSRmaxexportaangevuld),t(dt))
write.csv2(dt , "AnalysisresultsMSRmax.csv",row.names=FALSE)

dt = data.table(scenarionumber[index_scenarios,1:4],exportbaseloadmin[index_scenarios,])
exportname = c('Jaar','PV scenario','EV scenario','WP scenario',paste(exportnamelist,'.Bel1',sep=''),paste(exportnamelist,'.PV',sep=''),paste(exportnamelist,'.EV',sep=''),paste(exportnamelist,'.WP',sep=''))
dt = data.table(exportname,c(0,0,0,0,MSRmaxexportaangevuld),t(dt))
write.csv2(dt , "AnalysisresultsMSRmin.csv",row.names=FALSE)

print("--Done! Its ARRRrrrresome!--")
