# WriteOutput.R
# This script writes the output from Run.R into various formats to allow further calculations
# Main outputs:
# 1. VISION files to allow calculation of MS and OS loads in VISION
# 2. Excel files for high level analysis of key scenarios
# 3. Excel files for Financial model to determine required investments
# 4. RData structure for visualisation of output in Tableau 
#
# By Joris van der Els
# Based on code generated by Werner van Westering
# Start 21-12-2014
#
# Warning: This script contains no jokes at all
#
##Initialize ----------------------------------------------------------------------
# Remove all data and set working directory
rm(list=ls(all=TRUE))
gc(verbose=FALSE)
drive = substr(getwd(),1,3)
path = paste0(drive,"1. Programmeerwerk/Bottum Up Analyse/2. Data")
setwd(paste0(path,"/7. Output"))

print("--Loading packages--")
# Load packages
library(reshape2)
library(plyr)
library(data.table)
library(slam)       #Used for sparse matrices
library(tictoc)     #Because I am a Matlab person
library(xlsx)
library(ggplot2)
library(gmodels)

#Load data (To generate this data: run Run.R)
print("--Loading data (1/3)--")
load("CalculationOutput_NH_v2.RData")
drive = substr(getwd(),1,3)
path = paste0(drive,"1. Programmeerwerk/Bottum Up Analyse/2. Data")
setwd(paste0(path,"/7. Output"))

# Export to Finance output ----------------------------------------------------------------------------------
print("--Write export for finance (2/3)--")
setwd(paste0(path,"/7. Output/2. Finance"))
print("--> Defining scenarios for finance output (2a/3)--")
nFinscen      = 3
Fin_maxfeedin = c(1,3,1)  #[Low EV, high PV, low WP]
Fin_average   = c(2,2,2)  #[medium EV, medium PV, medium WP]
Fin_maxload   = c(4,1,3)  #[High EV, low PV, High WP]
Finscen       = rbind(Fin_maxfeedin,Fin_average,Fin_maxload)

print("--> Casting output to data tables for csv write  (2b/3)--")
scenariolistMSR  = c()
scenariocountMSR = c()
scenariolistHLD  = c()
scenariocountHLD = c()
scenariolist     = c()
scenariocount    = c()
Fin_index        = c()

# First create some vectors which will be used to index data in the finance model
for (i in 1:nFinscen) {
  name     = paste0("EV",scenarionamelist[Finscen[i,1]],"_PV",scenarionamelist[Finscen[i,2]],"_WP",scenarionamelist[Finscen[i,3]])
  nameMSR = rep(name,nMSR)
  nameHLD = rep(name,nHLD)
  scenariolistMSR = append(scenariolistMSR,nameMSR)
  scenariolistHLD = append(scenariolistHLD,nameHLD)
  scenariocountMSR = append(scenariocountMSR,rep(i,nMSR))
  scenariocountHLD = append(scenariocountHLD,rep(i,nHLD))
  index_start      = 1 + nyears * (
    ((Finscen[i,1]-1)*(dim(scenarionumber)[1]/(nEVscen)))+
      ((Finscen[i,2]-1)*(dim(scenarionumber)[1]/(nEVscen*nPVscen)))+
      ((Finscen[i,3]-1)*(dim(scenarionumber)[1]/(nEVscen*nPVscen*nWPscen))))
  index_end        = index_start + nyears - 1
  Fin_index        = cbind(Fin_index, seq(index_start,index_end))
}

scenariolist  = c(scenariolistMSR,scenariolistHLD)
scenariocount = c(scenariocountMSR,scenariocountHLD)

# Then build a function which will cast the input data 
CastFinanceMatrix <- function(df) {
  # First define indices
  ns            = nFinscen * nyears
  ns2           = 4 * nyears 
  nAssets       = dim(df)[1]/4
  Outputmatrix  = matrix(NA,nAssets*nFinscen,nyears*4)         #*4 for base, EV, PV, WP
  
  for (i in 1:nFinscen) {
    Assetindex = (1+(i-1)*nAssets):(i*nAssets)
    Yearindex  = (1+(i-1)*nyears):(i*nyears)
    Outputmatrix[Assetindex,1:nyears]                = df[1:nAssets,Yearindex]
    Outputmatrix[Assetindex,(1+nyears):(2*nyears)]   = df[(1+nAssets):(2*nAssets),Yearindex]
    Outputmatrix[Assetindex,(1+2*nyears):(3*nyears)] = df[(1+2*nAssets):(3*nAssets),Yearindex]
    Outputmatrix[Assetindex,(1+3*nyears):(4*nyears)] = df[(1+3*nAssets):(4*nAssets),Yearindex]
  }
  return(Outputmatrix)
}

# Cast data into correct order
dtMSR    = CastFinanceMatrix(MSRload_MSR[,Fin_index])
dtMSRmin = CastFinanceMatrix(MSRloadmin_MSR[,Fin_index])
dtHLD    = CastFinanceMatrix(HLDload_MSR[,Fin_index])
dtHLDmin = CastFinanceMatrix(HLDloadmin_MSR[,Fin_index])
data     = rbind(cbind(dtMSRmin,dtMSR),cbind(dtHLDmin,dtHLD))

# Define other vectors required for output
emptycol      = rep("",length(scenariolist))
net           = c(rep("MS",length(scenariolistMSR)),rep("LS",length(scenariolistHLD)))
type          = c(rep("trafo",length(scenariolistMSR)),rep("Kabel",length(scenariolistHLD)))
assetID       = c(rep(MSRlist,nFinscen),rep(HLD,nFinscen))
length        = c(rep("",(nFinscen*nMSR)),rep(HLDlength,nFinscen))
maxCap        = c(rep(MSRmax,nFinscen),rep(HLDmax,nFinscen))

# Cast data into data table
dt = data.table(emptycol,
                scenariocount,
                net,
                type,
                assetID,
                as.numeric(length),
                scenariolist,
                emptycol,emptycol,emptycol,emptycol,
                maxCap,
                emptycol,emptycol,emptycol,emptycol,emptycol,emptycol,
                data)


#set names
names = c()
years = startyear:endyear
for (i in c("-","+")) {
  for (j in c("Base","EV","PV","WP")) {
    names = c(names,paste0(j,"_",years,i))
  }
}
names = c("","scenarionummer","net","type","NR_Behuizing","Lengte","scenarioaanduiding",
          "","","","",
          "Nominaal vermogen",
          "","","","","","",
          names)
setnames(dt,names)

filename = paste0("Fin-output NHN_",Sys.Date(),".csv")
print("--> Write csv for Finance (2c/3)--")
write.csv2(dt,filename,row.names=FALSE)

# Export to VISION ----------------------------------------------------------------------------------------------
print("--Exporting to VISION (3/3)--")
print("--> Setting variables for VISION output (3a/3)--")
# Vision requires a very specific output format
indexlist         = match(MSRlist,Vnames$NR_Behuizing_NRG)                 # Cannot match 362 stations
Visionlist        = Vnames$ID_Vision[indexlist]                            # Sort the list of MSR's in the Vision order
NAlist            = is.na(Visionlist)==FALSE                               # Create a list of MSR that have not been found
exportnamelist    = Visionlist[NAlist]                                     # Only use the found MSR for the export         
NAlist            = rep(NAlist,4)
MSRexport         = MSRload_OSLD[NAlist,]
MSRexportmin      = MSRloadmin_OSLD[NAlist,]
nMSRexport        = dim(MSRexport)[1]
#indexlist         = c(seq(1,nMSRexport*nscenarios,by=4),seq(2,nMSRexport*nscenarios,by=4),seq(3,nMSRexport*nscenarios,by=4),seq(4,nMSRexport*nscenarios,by=4))
years             = seq(startyear,endyear)
datelist          = c(paste(rep_len(paste(years-2000,rep_len("-",nyears),rep.int(1,nyears),rep_len("-",nyears)),nscenarios),floor(seq.int(2001,2001+nscenarios/nyears,1/nyears))[1:nscenarios]))
datelistmin       = c(paste(rep_len(paste(years-2000,rep_len("-",nyears),rep.int(3,nyears),rep_len("-",nyears)),nscenarios),floor(seq.int(2001,2001+nscenarios/nyears,1/nyears))[1:nscenarios]))
timelist          = rep.int(9,nscenarios)
exportbaseload    = matrix(t(MSRexport),nscenarios,(nMSRexport))     # Reshape results for saving in Vision format
exportbaseloadmin = matrix(t(MSRexportmin),nscenarios,(nMSRexport))  # Reshape results for saving in Vision format
exportbaseload[is.na(exportbaseload)] = 0
exportbaseloadmin[is.na(exportbaseloadmin)] = 0

print("--> Casting output to data tables for csv write (3b/3)--")
#Set VISION output files and column names
exportname = c('Datum','Tijd',paste(exportnamelist,'.Bel1',sep=''),paste(exportnamelist,'.EV',sep=''),paste(exportnamelist,'.PV',sep=''),paste(exportnamelist,'.WP',sep='')) #Setup the specific Vision names
dt = data.table(datelist,timelist,exportbaseload)           #Convert exportmatrix to datatable because R is not capable enough to save matrices
dtmin = data.table(datelistmin,timelist,exportbaseloadmin)  #Convert exportmatrix to datatable because R is not capable enough to save matrices
setnames(dt,exportname)                                     #Set the column names
setnames(dtmin,exportname)                                  #Set the column names
dt2 = data.table(scenarionumber)
setnames(dt2,c('Scenario index','EV scenario', 'PV scenario', 'WP scenario'))
scenarioindex = scenarionumber[,1]

print("--> Write csv's for VISION (3c/3)--")
setwd(paste0(path,"/7. Output/1. VISION input"))
# write CSVs for VISION
progressbar = txtProgressBar(min = 0, max = length(scenarioindex), initial = 0, char = "=", style = 3)
tic()
for (ii in scenarioindex) {
  setTxtProgressBar(progressbar,ii)
  
  # First look up scenarios in vector scenarionumber
  EVii = scenarionumber[ii,2]  
  PVii = scenarionumber[ii,3] 
  WPii = scenarionumber[ii,4] 
  
  # Then print results for maxload scenario
  dtprint = dt[(1+(ii-1)*nyears):(ii*nyears),]
  name = paste0(ii,"a_MSRloadvision_EV",scenarionamelist[EVii],"_PV",scenarionamelist[PVii],"_WP",scenarionamelist[WPii],"_maxload",".csv")
  write.csv2(dtprint,name,row.names=FALSE)
  
  # And then for maxfeedin scenario
  dtprint = dtmin[(1+(ii-1)*nyears):(ii*nyears),]
  name = paste0(ii,"b_MSRloadvision_EV",scenarionamelist[EVii],"_PV",scenarionamelist[PVii],"_WP",scenarionamelist[WPii],"_maxfeedin",".csv")         
  write.csv2(dtprint,name,row.names=FALSE)
}
toc()
close(progressbar)

# Write identifiers for scenarios
write.csv2(dt2, "Scenarioindex.csv",)


# # Export to Excel for analysis ----------------------------------------------------------------------------------
# #Presentation_maxfeedin = [high PV, Low EV, low WP] = [3,1,1]
# #Presentation_average = [medium PV, medium EV, medium WP] = [1,3,4]
# #Presentation_maxload = [low PV, High EV, High WP] = [2,2,2]
# #select correct rows from output. 
# setwd(path)
# Presentation_maxload =  c(1,3,4) #[medium PV, medium EV, medium WP]
# Presentation_average = c(2,2,2) #[low PV, High EV, High WP]
# Presentation_maxfeedin = c(3,1,1) #[high PV, Low EV, low WP]
# index_maxload = seq(1 + ((Presentation_maxload[1]-1)* (nscenarios/3)) + ((Presentation_maxload[2]-1)* (nscenarios/12)) + ((Presentation_maxload[3]-1)* (nscenarios/48)),length.out=17)
# index_average = seq(1 + ((Presentation_average[1]-1)* (nscenarios/3)) + ((Presentation_average[2]-1)* (nscenarios/12)) + ((Presentation_average[3]-1)* (nscenarios/48)),length.out=17)
# index_maxfeedin = seq(1 + ((Presentation_maxfeedin[1]-1)* (nscenarios/3)) + ((Presentation_maxfeedin[2]-1)* (nscenarios/12)) + ((Presentation_maxfeedin[3]-1)* (nscenarios/48)),length.out=17)
# index_scenarios = c(index_maxload,index_average,index_maxfeedin)
# 
# MSRmaxexportaangevuld = c(MSRmaxexport,rep(0,3*nMSR))
# 
# dt = data.table(scenarionumber[index_scenarios,1:4],exportbaseload[index_scenarios,])
# exportname = c('Jaar','PV scenario','EV scenario','WP scenario',paste(exportnamelist,'.Bel1',sep=''),paste(exportnamelist,'.PV',sep=''),paste(exportnamelist,'.EV',sep=''),paste(exportnamelist,'.WP',sep=''))
# dt = data.table(exportname,c(0,0,0,0,MSRmaxexportaangevuld),t(dt))
# write.csv2(dt , "AnalysisresultsMSRmax.csv",row.names=FALSE)
# 
# dt = data.table(scenarionumber[index_scenarios,1:4],exportbaseloadmin[index_scenarios,])
# exportname = c('Jaar','PV scenario','EV scenario','WP scenario',paste(exportnamelist,'.Bel1',sep=''),paste(exportnamelist,'.PV',sep=''),paste(exportnamelist,'.EV',sep=''),paste(exportnamelist,'.WP',sep=''))
# dt = data.table(exportname,c(0,0,0,0,MSRmaxexportaangevuld),t(dt))
# write.csv2(dt , "AnalysisresultsMSRmin.csv",row.names=FALSE)

print("--Done! Its ARRRrrrresome!--")
